<?php

namespace App\Exports\DataCollection;

use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Events\AfterSheet;
use DB;
 
class Survey implements FromCollection, WithHeadings, WithTitle, ShouldAutoSize, 
    WithStyles
{
    protected $request;  

    function __construct($request) {
        $this->request = $request;
    }

    /**
    * @return \Illuminate\Support\Collection
    */
    public function collection()
    {

        $fixedList = [
            [
                'type' => 'select_one region', 
                'name' => 'select_region',
                'label:English (en)' => 'Select region',
                'label:Arabic (ar)' => 'اختر المدينة',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'select_one sub_region', 
                'name' => 'select_sub_region',
                'label:English (en)' => 'Select sub region',
                'label:Arabic (ar)' => 'اختر البلدة/القرية',
                'hint' => false,
                'choices' => 'sub_region',
                'choice_filter' => '${select_region} = region',
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'select_one community', 
                'name' => 'select_community',
                'label:English (en)' => 'Select community',
                'label:Arabic (ar)' => 'اختر التجمع',
                'hint' => false,
                'choices' => 'community',
                'choice_filter' => '${select_sub_region} = sub_region',
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'select_one compound', 
                'name' => 'select_compound',
                'label:English (en)' => 'Select compound',
                'label:Arabic (ar)' => 'اختر المنطقة داخل التجمع',
                'hint' => false,
                'choices' => 'compound',
                'choice_filter' => '${select_community} = community',
                'calculation' => false,
                'required' => 'no',
                'relevant' => false,
            ],
            [
                'type' => 'select_one household', 
                'name' => 'select_household_name',
                'label:English (en)' => 'Select household',
                'label:Arabic (ar)' => 'اختر العائلة',
                'hint' => false,
                'choices' => 'household', 
                'choice_filter' => '${select_community} = community',
                'calculation' => false,
                'required' => 'no',
                'relevant' => false,
            ],
            [
                'type' => 'select_one is_live', 
                'name' => 'select_is_live',
                'label:English (en)' => 'Do the household still live in the community, or move?',
                'label:Arabic (ar)' => 'هل العائلة موجودة بالتجمع أم رحلت/انتقلت؟',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],

            // Main Group
            [
                'type' => 'begin group', 
                'name' => 'live_left',
                'label:English (en)' => false,
                'label:Arabic (ar)' => false,
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => false,
                'relevant' => '${select_is_live} = "Live"',
            ],

            // First Group
            [
                'type' => 'begin group', 
                'name' => 'personal_details',
                'label:English (en)' => 'Personal Details',
                'label:Arabic (ar)' => 'المعلومات الشخصية',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => false,
                'relevant' => false,
            ],
            [
                'type' => 'text', 
                'name' => 'english_name',
                'label:English (en)' => 'Enter the household English name',
                'label:Arabic (ar)' => 'ادخل الاسم باللغة الانجليزية',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => 'pulldata("households", "label_en", "name", ${select_household_name})',
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'text', 
                'name' => 'arabic_name',
                'label:English (en)' => 'Enter the household Arabic name',
                'label:Arabic (ar)' => 'ادخل الاسم باللغة العربية',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => 'pulldata("households", "label_ar", "name", ${select_household_name})',
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'text', 
                'name' => 'household_status',
                'label:English (en)' => 'Household Status',
                'label:Arabic (ar)' => 'حالة المستخدم',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => 'pulldata("households", "household_status", "name", ${select_household_name})',
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'select_one profession', 
                'name' => 'select_profession',
                'label:English (en)' => 'Select profession',
                'label:Arabic (ar)' => 'اختر المهنة',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'integer', 
                'name' => 'phone_number',
                'label:English (en)' => 'Enter phone number',
                'label:Arabic (ar)' => 'ادخل رقم الهاتف',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'integer', 
                'name' => 'additional_phone_number',
                'label:English (en)' => 'Enter additional phone number',
                'label:Arabic (ar)' => 'ادخل رقم هاتف احتياطي',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'no',
                'relevant' => false,
            ],
            [
                'type' => 'end group', 
                'name' => false,
                'label:English (en)' => false,
                'label:Arabic (ar)' => false,
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => false,
                'relevant' => false,
            ],
            
            // Second Group
            [
                'type' => 'begin group', 
                'name' => 'family_members',
                'label:English (en)' => 'Family Members',
                'label:Arabic (ar)' => 'اعضاء الأسرة',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => false,
                'relevant' => false,
            ],
            [
                'type' => 'integer', 
                'name' => 'number_of_male',
                'label:English (en)' => 'Enter number of male',
                'label:Arabic (ar)' => 'عدد الذكور',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'integer', 
                'name' => 'number_of_female',
                'label:English (en)' => 'Enter number of female',
                'label:Arabic (ar)' => 'عدد الاناث',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'integer', 
                'name' => 'number_of_adults',
                'label:English (en)' => 'Enter number of adults',
                'label:Arabic (ar)' => 'عدد الكبار',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'integer', 
                'name' => 'number_of_children',
                'label:English (en)' => 'Enter number of children',
                'label:Arabic (ar)' => 'عدد الأطفال (أقل من 16 سنة)',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'integer', 
                'name' => 'school_students',
                'label:English (en)' => 'Enter number of school',
                'label:Arabic (ar)' => 'عدد طلاب المدارس',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'integer', 
                'name' => 'university_students',
                'label:English (en)' => 'Enter number of university',
                'label:Arabic (ar)' => 'عدد طلاب الجامعات',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'end group', 
                'name' => false,
                'label:English (en)' => false,
                'label:Arabic (ar)' => false,
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => false,
                'relevant' => false,
            ],		

            // Third Group
            [
                'type' => 'begin group', 
                'name' => 'services_status',
                'label:English (en)' => 'Services Status',
                'label:Arabic (ar)' => 'الخدمات',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => false,
                'relevant' => false,
            ],
            [
                'type' => 'select_one household_status', 
                'name' => 'select_household_status',
                'label:English (en)' => 'Select energy status',
                'label:Arabic (ar)' => 'اختر حالة المستخدم',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'text', 
                'name' => 'meter_number',
                'label:English (en)' => 'Meter number',
                'label:Arabic (ar)' => 'رقم الساعة',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => 'pulldata("households", "meter_number", "name", ${select_household_name})',
                'required' => 'no',
                'relevant' => '${select_household_status} = "Served"',
            ],
            [
                'type' => 'select_one meter_case', 
                'name' => 'select_meter_case',
                'label:English (en)' => 'Select meter case',
                'label:Arabic (ar)' => 'اختر حالة ساعة الكهرباء',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => '${select_household_status} = "Served"',
            ],
            [
                'type' => 'select_one meter_case_description', 
                'name' => 'select_meter_case_description',
                'label:English (en)' => 'Select meter case description',
                'label:Arabic (ar)' => 'اختر السبب',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => '${select_meter_case} = "Low usage" or ${select_meter_case} = "Not used"  or ${select_meter_case} = "Bypass meter" or ${select_meter_case} = "Left Comet"',
            ],
            [
                'type' => 'select_one main_user', 
                'name' => 'select_main_user',
                'label:English (en)' => 'Select main user',
                'label:Arabic (ar)' => 'اختر مشترك مع من',
                'hint' => false,
                'choices' => 'main_user',
                'choice_filter' => '${select_community} = community',
                'calculation' => false,
                'required' => 'yes',
                'relevant' => '${select_household_status} = "Shared" or ${select_household_status} = "Shared & Requested"',
            ],
            [
                'type' => 'select_one system_type', 
                'name' => 'select_system_type',
                'label:English (en)' => 'Select System type',
                'label:Arabic (ar)' => 'نوع النظام الذي يطلبه',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => '${select_household_status} = "Requested" or ${select_household_status} = "Shared & Requested"',
            ],
            [
                'type' => 'select_one water', 
                'name' => 'select_water_system_status',
                'label:English (en)' => 'Select water status',
                'label:Arabic (ar)' => 'هل يوجد عنده نظام ماء',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'select_one internet', 
                'name' => 'select_internet_system_status',
                'label:English (en)' => 'Select internet status',
                'label:Arabic (ar)' => 'هل يوجد عنده انترنت',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'select_one refrigerator', 
                'name' => 'select_refrigerator',
                'label:English (en)' => 'Select refrigerator',
                'label:Arabic (ar)' => 'هل يوجد لديه ثلاجة من كوميت',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'end group', 
                'name' => false,
                'label:English (en)' => false,
                'label:Arabic (ar)' => false,
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => false,
                'relevant' => false,
            ],
							
            // Fourth Group
            [
                'type' => 'begin group', 
                'name' => 'house_details',
                'label:English (en)' => 'House Details',
                'label:Arabic (ar)' => 'تفاصيل المنزل',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => false,
                'relevant' => false,
            ],
            [
                'type' => 'select_one demolition', 
                'name' => 'demolition_order',
                'label:English (en)' => 'Select demolition order',
                'label:Arabic (ar)' => 'هل يوجد لديه أوامر هدم',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'select_one house', 
                'name' => 'select_is_there_house_in_town',
                'label:English (en)' => 'Select house in the town',
                'label:Arabic (ar)' => 'هل يوجد بيت في القرية/البلدة',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'end group', 
                'name' => false,
                'label:English (en)' => false,
                'label:Arabic (ar)' => false,
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => false,
                'relevant' => false,
            ],

            // Fifth Group
            [
                'type' => 'begin group', 
                'name' => 'herds',
                'label:English (en)' => 'Herds',
                'label:Arabic (ar)' => 'الأغنام',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => false,
                'relevant' => false,
            ],
            [
                'type' => 'select_one herds', 
                'name' => 'select_herd',
                'label:English (en)' => 'Select herd',
                'label:Arabic (ar)' => 'هل يوجد غنم',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'integer', 
                'name' => 'size_of_herd',
                'label:English (en)' => 'Enter size of herds',
                'label:Arabic (ar)' => 'ادخل عدد الأغنام',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'no',
                'relevant' => '${select_herd} = "Yes"',
            ],
            [
                'type' => 'integer', 
                'name' => 'number_of_animal_shelters',
                'label:English (en)' => 'Enter number of animal shelter',
                'label:Arabic (ar)' => 'كم عدد بيوت الغنم (البركسات)',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'no',
                'relevant' => '${select_herd} = "Yes"',
            ],
            [
                'type' => 'end group', 
                'name' => false,
                'label:English (en)' => false,
                'label:Arabic (ar)' => false,
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => false,
                'relevant' => false,
            ],

            // Sixth Group
            [
                'type' => 'begin group', 
                'name' => 'cistern',
                'label:English (en)' => 'Cistern',
                'label:Arabic (ar)' => 'الآبار',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => false,
                'relevant' => false,
            ],
            [
                'type' => 'select_one cistern', 
                'name' => 'select_cistern',
                'label:English (en)' => 'Select cistern',
                'label:Arabic (ar)' => 'هل يوجد بئر ماء',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'integer', 
                'name' => 'number_of_cisterns',
                'label:English (en)' => 'Enter how many cisterns',
                'label:Arabic (ar)' => 'كم عدد آبار الماء',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'no',
                'relevant' => '${select_cistern} = "Yes"',
            ],
            [
                'type' => 'integer', 
                'name' => 'cistern_depth',
                'label:English (en)' => 'Enter the depth in Liter',
                'label:Arabic (ar)' => 'كم حجم البئر بالكوب',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'no',
                'relevant' => '${select_cistern} = "Yes"',
            ],
            [
                'type' => 'integer', 
                'name' => 'distance_from_house',
                'label:English (en)' => 'Enter the distance in meter',
                'label:Arabic (ar)' => 'كم يبعد عن المنزل (بالمتر)',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'no',
                'relevant' => '${select_cistern} = "Yes"',
            ],
            [
                'type' => 'select_one shared_cistern', 
                'name' => 'select_shared_cisterns',
                'label:English (en)' => 'Select cistern shared',
                'label:Arabic (ar)' => 'هل البئر مشترك',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'no',
                'relevant' => '${select_cistern} = "Yes"',
            ],
            [
                'type' => 'end group', 
                'name' => false,
                'label:English (en)' => false,
                'label:Arabic (ar)' => false,
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => false,
                'relevant' => false,
            ],

            // Seventh Group
            [
                'type' => 'begin group', 
                'name' => 'izbih',
                'label:English (en)' => 'Izbih',
                'label:Arabic (ar)' => 'العزبة',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => false,
                'relevant' => false,
            ],
            [
                'type' => 'select_one izbih', 
                'name' => 'select_is_there_izbih',
                'label:English (en)' => 'Select Izbih',
                'label:Arabic (ar)' => 'هل يعزب',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'yes',
                'relevant' => false,
            ],
            [
                'type' => 'integer', 
                'name' => 'how_long',
                'label:English (en)' => 'Enter how long',
                'label:Arabic (ar)' => 'كم يمكث بالعزبة (بالأشهر)',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'no',
                'relevant' => '${select_is_there_izbih} = "Yes"',
            ],
            [
                'type' => 'end group', 
                'name' => false,
                'label:English (en)' => false,
                'label:Arabic (ar)' => false,
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => false,
                'relevant' => false,
            ],

            [
                'type' => 'end group', 
                'name' => false,
                'label:English (en)' => false,
                'label:Arabic (ar)' => false,
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => false,
                'relevant' => false,
            ],		
            [
                'type' => 'text', 
                'name' => 'household_notes',
                'label:English (en)' => 'Enter notes',
                'label:Arabic (ar)' => 'ملاحظات',
                'hint' => false,
                'choices' => false,
                'choice_filter' => false,
                'calculation' => false,
                'required' => 'no',
                'relevant' => false,
                'appearance' => 'long-text'
            ],		

        ];
        
        $fixedListCollection = collect($fixedList);

        return $fixedListCollection;
    }

    /**
     * Write code on Method
     *
     * @return response()
     */
    public function headings(): array
    {
        return ['type', 'name', 'label:English (en)', 'label:Arabic (ar)', 'hint', 'choices', 
            'choice_filter', 'calculation', 'required', 'relevant', 'appearance'];
    }


    public function title(): string
    {
        return 'survey';
    }

    public function startCell(): string
    {
        return 'A1';
    } 


    /**
     * Styling
     *
     * @return response()
     */
    public function styles(Worksheet $sheet)
    {
        $sheet->setAutoFilter('A1:I1');

        return [
            // Style the first row as bold text.
            1 => ['font' => ['bold' => true, 'size' => 12]],
        ];
    }
}